### ISSUE TITLE
Regarding evaluation metrics for segmentation results

### ISSUE THREAD

**Issue by weihao94** [Thvnvtos/Lung_Segmentation#4]
Hi , sorry to bother you again, but I will like to ask if you have compared your methods with other state-of-the-art methods by other people/researchers. 

If you did, are you intending to publish the results? Reason is for citation purposes.

Also, if you did obtain some evaluation metrics (e.g. DICE scores, etc), will it be possible to make public a script that does that? It'll help the community standardize results comparisons and benchmarking during this troubling times. :)

Thank you.

**Comment by Thvnvtos** [comment]
I only used DICE score both for training and evaluation, I did not do a thorough evaluation since this is not a research project, the model used here is a vanilla 3D UNet, I obtained good results because at the time I had access to powerful GPUs, to train a model like this on this type of data without having to harshly reduce the dimensions requires a lot of GPU memory.

**Comment by weihao94** [comment]
@Thvnvtos Thanks for the clarifications, appreciate it. I agree on the GPU requirements part, it can get really bad if the architecture is not efficient. Thankfully, recent advancements on 3D segmentation architectures have enabled U-Net variants to utilize significantly less GPU without sacrificing accuracies. Thanks again!
